export const copy = {
  en: {
    nav: {
      dm: 'Direct Messages',
      agents: 'Agent Messages',
      history: 'Inbox / Sent',
      about: 'About Arcanum',
      faq: 'FAQ',
    },
    header: {
      tagline: 'Private on-chain messaging on Arc Testnet.',
      connect: 'Connect Wallet',
      connecting: 'Connecting...',
      disconnect: 'Disconnect',
      ready: 'Arc ready',
      wrong: 'Wrong network',
      switch: 'Switch to Arc',
      switching: 'Switching...',
      contract: 'Contract',
      menu: 'Open menu',
      close: 'Close menu',
      live: 'On-chain',
    },
    sidebar: {
      protocol: 'Protocol',
      status: 'Status',
      wallet: 'Wallet',
      messages: 'Messages',
      security: 'Security',
      keyCenter: 'Key Center',
      openKeyCenter: 'Open Key Center',
      contract: 'Contract',
    },
    key: {
      ok: 'Key registered',
      needed: 'Key required',
      register: 'Register key',
      unlock: 'Unlock key',
      locked: 'Local key locked',
      localReady: 'Local key ready',
      noLocal: 'No local key',
      export: 'Export key',
      import: 'Import key',
      createTitle: 'Register encryption key',
      unlockTitle: 'Unlock local key',
      exportTitle: 'Export encrypted backup',
      importTitle: 'Import encrypted backup',
      createBody: 'Create a passphrase for this device key. You will need it to unlock private messages.',
      unlockBody: 'Enter your Arcanum key passphrase to unlock private messages on this device.',
      exportBody: 'Enter a passphrase to encrypt the backup file before it downloads.',
      importBody: 'Choose your backup file and enter the passphrase used during export.',
      passphrase: 'Passphrase',
      file: 'Backup file',
      chooseFile: 'Choose JSON backup',
      selectedFile: 'Selected file',
      confirm: 'Continue',
      cancel: 'Cancel',
      centerTitle: 'Key Center',
      centerBody: 'Private messages require both an on-chain public key and a local encrypted private key.',
      onChain: 'On-chain public key',
      local: 'Local private key',
    },
    dm: {
      title: 'Direct Messages',
      newChat: 'New DM address',
      recipient: '0x recipient address',
      search: 'Search address',
      empty: 'No conversations yet',
      choose: 'Choose a conversation or enter a recipient address.',
      noWallet: 'Connect your wallet to load conversations.',
      encrypted: 'Encrypted payload is stored on-chain.',
      keyRequired: 'Import or unlock this wallet encryption key to read this private message.',
      decryptFailed: 'This private message could not be decrypted with the key on this device.',
      selected: 'Selected conversation',
      noPreview: 'Private message',
      newConversation: 'New conversation',
      pendingHint: 'Waiting for on-chain confirmation',
    },
    composer: {
      placeholder: 'Write a message...',
      private: 'Private',
      public: 'Public',
      send: 'Send on-chain',
      waiting: 'Wallet confirmation...',
      invalid: 'Enter a valid EVM address.',
      self: 'You cannot message your own wallet.',
      missingKey: 'Recipient must register an Arcanum encryption key before private messages can be sent.',
      privateHint: 'Private messages are encrypted in the browser before they are written on-chain.',
      publicHint: 'Public messages are written to the chain as plaintext and can be read by anyone.',
      publicWarning: 'Public mode stores readable plaintext on-chain permanently.',
      fee: 'Fee',
      chars: 'characters',
    },
    history: {
      title: 'Inbox / Sent',
      inbox: 'Inbox',
      sent: 'Sent',
      refresh: 'Refresh',
      empty: 'This message stream is empty.',
      reply: 'Reply',
      open: 'Open chat',
      from: 'From',
      to: 'To',
      time: 'Time',
      loadMore: 'Load more',
      loaded: 'Loaded',
    },
    about: [
      'Arcanum is a private on-chain messaging dApp running on Arc Testnet.',
      'Public messages are written to the chain as readable plaintext payloads.',
      'Private messages are encrypted in the browser and only ciphertext is stored on-chain.',
      'Encryption keys stay in the browser. Export/import the encrypted key backup to read old private messages on another device.',
    ],
    faq: [
      ['What is Arc Testnet?', 'Arc Testnet is the network where Arcanum currently writes and reads message records.'],
      ['Why register an encryption key?', 'Private messaging needs the recipient public key on-chain so the browser can encrypt before sending.'],
      ['Where are private messages stored?', 'Only encrypted ciphertext and metadata are stored on-chain. Readable text exists after client-side decryption.'],
      ['How do I read old private messages elsewhere?', 'Export your encrypted key backup and import it on the new device with the same passphrase.'],
      ['Why is the gas token USDC?', 'Arc Testnet uses USDC as its native gas token in the current configuration.'],
      ['Can I delete or edit messages?', 'No. The current contract stores immutable on-chain messages.'],
    ],
    status: {
      idle: 'No active transaction.',
      preparingKey: 'Preparing encryption key...',
      wallet: 'Waiting for wallet confirmation...',
      keyPending: 'Key registration is pending on-chain...',
      keyFailed: 'Key registration failed.',
      encrypting: 'Encrypting message in the browser...',
      preparingMessage: 'Preparing message...',
      pending: 'Transaction is pending on-chain...',
      success: 'Transaction confirmed. Message was written on-chain.',
      failed: 'Message could not be sent.',
      rejected: 'Wallet request was rejected.',
      insufficient: 'Insufficient Arc Testnet USDC for gas or message fee.',
      switchRejected: 'Arc Testnet switch was rejected or could not be added.',
      missingKey: 'Recipient does not have an encryption key yet. They must register in Arcanum first.',
      exported: 'Encrypted key backup downloaded.',
      imported: 'Key backup imported on this device.',
      unlocked: 'Local encryption key unlocked for this session.',
      unlockFailed: 'Local encryption key could not be unlocked.',
      mismatch: 'Key imported, but it does not match the on-chain key. Register the imported key before receiving new private messages.',
      backupFailed: 'Key backup action failed.',
      explorer: 'Explorer',
      steps: ['Prepare', 'Wallet', 'Pending', 'Confirmed'],
    },
    common: {
      private: 'Private',
      public: 'Public',
      disconnected: 'Wallet disconnected',
      unavailable: 'Contract address is not configured.',
      connected: 'Connected',
      disconnectedShort: 'Disconnected',
      empty: 'Empty state',
    },
  },
  tr: {
    nav: {
      dm: 'Direkt Mesajlar',
      agents: 'Agent Mesajlari',
      history: 'Inbox / Sent',
      about: 'Arcanum Hakkında',
      faq: 'SSS',
    },
    header: {
      tagline: 'Arc Testnet üzerinde gizli on-chain mesajlaşma.',
      connect: 'Cüzdanı Bağla',
      connecting: 'Bağlanıyor...',
      disconnect: 'Bağlantıyı Kes',
      ready: 'Arc hazır',
      wrong: 'Yanlış ağ',
      switch: 'Arc ağına geç',
      switching: 'Geçiliyor...',
      contract: 'Kontrat',
      menu: 'Menüyü aç',
      close: 'Menüyü kapat',
      live: 'On-chain',
    },
    sidebar: {
      protocol: 'Protokol',
      status: 'Durum',
      wallet: 'Cüzdan',
      messages: 'Mesajlar',
      security: 'Güvenlik',
      keyCenter: 'Key Center',
      openKeyCenter: 'Key Center aç',
      contract: 'Kontrat',
    },
    key: {
      ok: 'Key kayıtlı',
      needed: 'Key gerekli',
      register: 'Key kaydet',
      unlock: 'Key kilidini aç',
      locked: 'Local key kilitli',
      localReady: 'Local key hazır',
      noLocal: 'Local key yok',
      export: 'Key dışa aktar',
      import: 'Key içe aktar',
      createTitle: 'Encryption key kaydet',
      unlockTitle: 'Local key kilidini aç',
      exportTitle: 'Şifreli backup dışa aktar',
      importTitle: 'Şifreli backup içe aktar',
      createBody: 'Bu cihazdaki key için parola oluştur. Private mesajları açmak için bu parola gerekecek.',
      unlockBody: 'Bu cihazdaki private mesajları açmak için Arcanum key parolanı gir.',
      exportBody: 'Backup dosyası indirilmeden önce şifrelemek için bir parola gir.',
      importBody: 'Backup dosyanı seç ve export sırasında kullandığın parolayı gir.',
      passphrase: 'Parola',
      file: 'Backup dosyası',
      chooseFile: 'JSON backup seç',
      selectedFile: 'Seçili dosya',
      confirm: 'Devam et',
      cancel: 'Vazgeç',
      centerTitle: 'Key Center',
      centerBody: 'Private mesajlar için zincirde public key ve cihazda şifreli private key gerekir.',
      onChain: 'On-chain public key',
      local: 'Local private key',
    },
    dm: {
      title: 'Direkt Mesajlar',
      newChat: 'Yeni DM adresi',
      recipient: '0x alıcı adresi',
      search: 'Adres ara',
      empty: 'Henüz konuşma yok',
      choose: 'Bir konuşma seç veya yeni alıcı adresi gir.',
      noWallet: 'Konuşmaları yüklemek için cüzdanını bağla.',
      encrypted: 'Şifreli payload zincirde saklanıyor.',
      keyRequired: 'Bu private mesajı okumak için bu wallet encryption keyini import et veya unlock et.',
      decryptFailed: 'Bu gizli mesaj bu cihazdaki anahtarla çözülemedi.',
      selected: 'Seçili konuşma',
      noPreview: 'Private mesaj',
      newConversation: 'Yeni konuşma',
      pendingHint: 'On-chain onay bekleniyor',
    },
    composer: {
      placeholder: 'Mesaj yaz...',
      private: 'Private',
      public: 'Public',
      send: 'Zincire gönder',
      waiting: 'Cüzdan onayı bekleniyor...',
      invalid: 'Geçerli bir EVM adresi gir.',
      self: 'Kendi cüzdanına mesaj gönderemezsin.',
      missingKey: 'Private mesaj için alıcı önce Arcanum şifreleme anahtarı kaydetmeli.',
      privateHint: 'Private mesajlar zincire yazılmadan önce browser içinde şifrelenir.',
      publicHint: 'Public mesajlar zincire plaintext olarak yazılır ve herkes tarafından okunabilir.',
      publicWarning: 'Public mod okunabilir metni kalıcı olarak zincire yazar.',
      fee: 'Fee',
      chars: 'karakter',
    },
    history: {
      title: 'Inbox / Sent',
      inbox: 'Inbox',
      sent: 'Sent',
      refresh: 'Yenile',
      empty: 'Bu mesaj akışı şu an boş.',
      reply: 'Yanıtla',
      open: 'Chat aç',
      from: 'Kimden',
      to: 'Kime',
      time: 'Zaman',
      loadMore: 'Daha fazla yükle',
      loaded: 'Yüklendi',
    },
    about: [
      'Arcanum, Arc Testnet üzerinde çalışan private on-chain messaging dApp uygulamasıdır.',
      'Public mesajlar zincire okunabilir plaintext payload olarak yazılır.',
      'Private mesajlar browser içinde şifrelenir ve zincirde yalnızca ciphertext saklanır.',
      'Şifreleme anahtarları browserda kalır. Başka cihazda eski private mesajları okumak için şifreli key backup export/import kullanılır.',
    ],
    faq: [
      ['Arc Testnet nedir?', 'Arcanum mesaj kayıtlarını şu an Arc Testnet üzerinde yazar ve okur.'],
      ['Neden encryption key kaydı gerekiyor?', 'Private mesaj için alıcının public key bilgisi zincirde olmalı ki browser mesajı göndermeden önce şifreleyebilsin.'],
      ['Private mesajlar nerede saklanıyor?', 'Zincirde yalnızca şifreli ciphertext ve metadata saklanır. Okunabilir metin decrypt sonrası client tarafındadır.'],
      ['Başka cihazda eski private mesajları nasıl okuyabilirim?', 'İlk browserdan şifreli key backup dosyasını export edip yeni cihazda aynı parola ile import etmelisin.'],
      ['Gas token neden USDC?', 'Arc Testnet mevcut yapılandırmada native gas token olarak USDC kullanır.'],
      ['Mesaj silme veya düzenleme var mı?', 'Hayır. Mevcut kontrat immutable on-chain mesaj saklar.'],
    ],
    status: {
      idle: 'Aktif işlem yok.',
      preparingKey: 'Şifreleme anahtarı hazırlanıyor...',
      wallet: 'Cüzdan onayı bekleniyor...',
      keyPending: 'Anahtar kayıt işlemi zincirde bekliyor...',
      keyFailed: 'Anahtar kaydı başarısız oldu.',
      encrypting: 'Mesaj browser içinde şifreleniyor...',
      preparingMessage: 'Mesaj hazırlanıyor...',
      pending: 'İşlem zincirde bekliyor...',
      success: 'İşlem onaylandı. Mesaj zincire yazıldı.',
      failed: 'Mesaj gönderilemedi.',
      rejected: 'Cüzdan isteği reddedildi.',
      insufficient: 'Gas veya mesaj fee için Arc Testnet USDC yetersiz.',
      switchRejected: 'Arc Testnet geçişi reddedildi veya ağ eklenemedi.',
      missingKey: 'Alıcının şifreleme anahtarı yok. Alıcı önce Arcanum’a kayıt olmalı.',
      exported: 'Şifreli key backup dosyası indirildi.',
      imported: 'Key backup bu cihaza aktarıldı.',
      unlocked: 'Local encryption key bu oturum için açıldı.',
      unlockFailed: 'Local encryption key açılamadı.',
      mismatch: 'Key import edildi, ancak zincirdeki key ile eşleşmiyor. Yeni private mesajlar için import edilen key’i tekrar kaydet.',
      backupFailed: 'Key backup işlemi başarısız oldu.',
      explorer: 'Explorer',
      steps: ['Hazırla', 'Cüzdan', 'Pending', 'Onaylandı'],
    },
    common: {
      private: 'Private',
      public: 'Public',
      disconnected: 'Cüzdan bağlı değil',
      unavailable: 'Kontrat adresi yapılandırılmamış.',
      connected: 'Bağlı',
      disconnectedShort: 'Bağlı değil',
      empty: 'Boş durum',
    },
  },
} as const;

export type Language = 'en' | 'tr';
