export const copy = {
  en: {
    nav: ['Direct Messages', 'Inbox / Sent', 'About Arcanum', 'FAQ'],
    header: {
      tagline: 'Private on-chain messaging on Arc Testnet.',
      connect: 'Connect Wallet',
      connecting: 'Connecting...',
      disconnect: 'Disconnect',
      ready: 'Network ready',
      wrong: 'Wrong network',
      switch: 'Switch to Arc',
      switching: 'Switching...',
      contract: 'Contract',
      menu: 'Open menu',
    },
    key: {
      ok: 'Key registered',
      needed: 'Key required',
      register: 'Register key',
      export: 'Export key',
      import: 'Import key',
      exportPrompt: 'Enter a passphrase to encrypt your key backup.',
      importPrompt: 'Enter the passphrase for this key backup.',
    },
    dm: {
      title: 'Direct Messages',
      newChat: 'New DM address',
      recipient: '0x recipient address',
      empty: 'No conversations yet',
      choose: 'Choose a conversation or enter a recipient address.',
      noWallet: 'Connect your wallet to load conversations.',
      encrypted: 'Encrypted payload is stored on-chain.',
      decryptFailed: 'This private message could not be decrypted with the key on this device.',
    },
    composer: {
      placeholder: 'Write a message...',
      private: 'Private',
      public: 'Public',
      send: 'Send on-chain',
      waiting: 'Wallet confirmation...',
      invalid: 'Enter a valid EVM address.',
      self: 'You cannot message your own wallet.',
      missingKey: 'Recipient must register an Arcanum encryption key before private messages can be sent.',
      privateHint: 'Private messages are encrypted in the browser before they are written on-chain.',
      publicHint: 'Public messages are written to the chain as plaintext.',
      fee: 'Fee',
    },
    history: {
      title: 'Inbox / Sent',
      inbox: 'Inbox',
      sent: 'Sent',
      refresh: 'Refresh',
      empty: 'This message stream is empty.',
      reply: 'Reply',
      open: 'Open chat',
      from: 'From',
      to: 'To',
      time: 'Time',
    },
    about: [
      'Arcanum is a private on-chain messaging dApp running on Arc Testnet.',
      'Public messages are written to the chain as readable plaintext payloads.',
      'Private messages are encrypted in the browser and only ciphertext is stored on-chain.',
      'Encryption keys stay in the browser. Export/import the encrypted key backup to read old private messages on another device.',
    ],
    faq: [
      ['What is Arc Testnet?', 'Arc Testnet is the network where Arcanum currently writes and reads message records.'],
      ['Why register an encryption key?', 'Private messaging needs the recipient public key on-chain so the browser can encrypt before sending.'],
      ['Where are private messages stored?', 'Only encrypted ciphertext and metadata are stored on-chain. Readable text exists after client-side decryption.'],
      ['How do I read old private messages elsewhere?', 'Export your encrypted key backup and import it on the new device with the same passphrase.'],
      ['Why is the gas token USDC?', 'Arc Testnet uses USDC as its native gas token in the current configuration.'],
      ['Can I delete or edit messages?', 'No. The current contract stores immutable on-chain messages.'],
    ],
    status: {
      preparingKey: 'Preparing encryption key...',
      wallet: 'Waiting for wallet confirmation...',
      keyPending: 'Key registration is pending on-chain...',
      keyFailed: 'Key registration failed.',
      encrypting: 'Encrypting message in the browser...',
      preparingMessage: 'Preparing message...',
      pending: 'Transaction is pending on-chain...',
      success: 'Transaction confirmed. Message was written on-chain.',
      failed: 'Message could not be sent.',
      switchRejected: 'Arc Testnet switch was rejected or could not be added.',
      missingKey: 'Recipient does not have an encryption key yet. They must register in Arcanum first.',
      exported: 'Encrypted key backup downloaded.',
      imported: 'Key backup imported on this device.',
      mismatch: 'Key imported, but it does not match the on-chain key. Register the imported key before receiving new private messages.',
      backupFailed: 'Key backup action failed.',
      explorer: 'Explorer',
    },
    common: {
      private: 'Private',
      public: 'Public',
      disconnected: 'Wallet disconnected',
      unavailable: 'Contract address is not configured.',
    },
  },
  tr: {
    nav: ['Direkt Mesajlar', 'Inbox / Sent', 'Arcanum Hakkında', 'SSS'],
    header: {
      tagline: 'Arc Testnet üzerinde gizli on-chain mesajlaşma.',
      connect: 'Cüzdanı Bağla',
      connecting: 'Bağlanıyor...',
      disconnect: 'Bağlantıyı kes',
      ready: 'Ağ hazır',
      wrong: 'Yanlış ağ',
      switch: 'Arc ağına geç',
      switching: 'Geçiliyor...',
      contract: 'Kontrat',
      menu: 'Menüyü aç',
    },
    key: {
      ok: 'Key registered',
      needed: 'Key required',
      register: 'Register key',
      export: 'Export key',
      import: 'Import key',
      exportPrompt: 'Key backup dosyasını şifrelemek için bir parola gir.',
      importPrompt: 'Bu key backup dosyasının parolasını gir.',
    },
    dm: {
      title: 'Direkt Mesajlar',
      newChat: 'Yeni DM adresi',
      recipient: '0x alıcı adresi',
      empty: 'Henüz konuşma yok',
      choose: 'Bir konuşma seç veya yeni alıcı adresi gir.',
      noWallet: 'Konuşmaları yüklemek için cüzdanını bağla.',
      encrypted: 'Şifreli payload zincirde saklanıyor.',
      decryptFailed: 'Bu gizli mesaj bu cihazdaki anahtarla çözülemedi.',
    },
    composer: {
      placeholder: 'Mesaj yaz...',
      private: 'Private',
      public: 'Public',
      send: 'Zincire gönder',
      waiting: 'Cüzdan onayı bekleniyor...',
      invalid: 'Geçerli bir EVM adresi gir.',
      self: 'Kendi cüzdanına mesaj gönderemezsin.',
      missingKey: 'Private mesaj için alıcı önce Arcanum şifreleme anahtarı kaydetmeli.',
      privateHint: 'Private mesajlar zincire yazılmadan önce browser içinde şifrelenir.',
      publicHint: 'Public mesajlar zincire plaintext olarak yazılır.',
      fee: 'Fee',
    },
    history: {
      title: 'Inbox / Sent',
      inbox: 'Inbox',
      sent: 'Sent',
      refresh: 'Yenile',
      empty: 'Bu mesaj akışı şu an boş.',
      reply: 'Yanıtla',
      open: 'Chat aç',
      from: 'From',
      to: 'To',
      time: 'Time',
    },
    about: [
      'Arcanum, Arc Testnet üzerinde çalışan private on-chain messaging dApp uygulamasıdır.',
      'Public mesajlar zincire okunabilir plaintext payload olarak yazılır.',
      'Private mesajlar browser içinde şifrelenir ve zincirde yalnızca ciphertext saklanır.',
      'Şifreleme anahtarları browserda kalır. Başka cihazda eski private mesajları okumak için şifreli key backup export/import kullanılır.',
    ],
    faq: [
      ['Arc Testnet nedir?', 'Arcanum mesaj kayıtlarını şu an Arc Testnet üzerinde yazar ve okur.'],
      ['Neden encryption key kaydı gerekiyor?', 'Private mesaj için alıcının public key bilgisi zincirde olmalı ki browser mesajı göndermeden önce şifreleyebilsin.'],
      ['Private mesajlar nerede saklanıyor?', 'Zincirde yalnızca şifreli ciphertext ve metadata saklanır. Okunabilir metin decrypt sonrası client tarafındadır.'],
      ['Başka cihazda eski private mesajları nasıl okuyabilirim?', 'İlk browserdan şifreli key backup dosyasını export edip yeni cihazda aynı parola ile import etmelisin.'],
      ['Gas token neden USDC?', 'Arc Testnet mevcut yapılandırmada native gas token olarak USDC kullanır.'],
      ['Mesaj silme veya düzenleme var mı?', 'Hayır. Mevcut kontrat immutable on-chain mesaj saklar.'],
    ],
    status: {
      preparingKey: 'Şifreleme anahtarı hazırlanıyor...',
      wallet: 'Cüzdan onayı bekleniyor...',
      keyPending: 'Anahtar kayıt işlemi zincirde bekliyor...',
      keyFailed: 'Anahtar kaydı başarısız oldu.',
      encrypting: 'Mesaj browser içinde şifreleniyor...',
      preparingMessage: 'Mesaj hazırlanıyor...',
      pending: 'İşlem zincirde bekliyor...',
      success: 'İşlem onaylandı. Mesaj zincire yazıldı.',
      failed: 'Mesaj gönderilemedi.',
      switchRejected: 'Arc Testnet geçişi reddedildi veya ağ eklenemedi.',
      missingKey: 'Alıcının şifreleme anahtarı yok. Alıcı önce Arcanum’a kayıt olmalı.',
      exported: 'Şifreli key backup dosyası indirildi.',
      imported: 'Key backup bu cihaza aktarıldı.',
      mismatch: 'Key import edildi, ancak zincirdeki key ile eşleşmiyor. Yeni private mesajlar için import edilen key’i tekrar kaydet.',
      backupFailed: 'Key backup işlemi başarısız oldu.',
      explorer: 'Explorer',
    },
    common: {
      private: 'Private',
      public: 'Public',
      disconnected: 'Cüzdan bağlı değil',
      unavailable: 'Kontrat adresi yapılandırılmamış.',
    },
  },
} as const;

export type Language = 'en' | 'tr';
